name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  # System libgit2 via pkg-config (probe path).
  system-libgit2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codename:
          - bookworm
        perl-version:
          - '5.36'
          - '5.38'
          - '5.40'
    container:
      image: perl:${{ matrix.perl-version }}-${{ matrix.codename }}
    steps:
      - uses: actions/checkout@v4
      - name: Fix safe.directory
        run: git config --global --add safe.directory /__w/p5-alien-libgit2/p5-alien-libgit2
      - name: perl -V
        run: perl -V
      - name: Install build prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            libgit2-dev pkg-config git
      - name: Install Dist::Zilla
        env:
          PERL_CPANM_OPT: --mirror http://cpan.metacpan.org --mirror-only
        run: cpanm -nq Dist::Zilla Dist::Zilla::PluginBundle::Author::GETTY && dzil install
      - name: Install dependencies
        env:
          PERL_CPANM_OPT: --mirror http://cpan.metacpan.org --mirror-only
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --missing | cpanm -nq
      - name: Run tests
        run: dzil test

  # Share build (vendored libgit2 + cmake).
  share-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codename:
          - bookworm
        perl-version:
          - '5.40'
    container:
      image: perl:${{ matrix.perl-version }}-${{ matrix.codename }}
    steps:
      - uses: actions/checkout@v4
      - name: Fix safe.directory
        run: git config --global --add safe.directory /__w/p5-alien-libgit2/p5-alien-libgit2
      - name: Install build prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            cmake build-essential libssl-dev libssh2-1-dev zlib1g-dev pkg-config git
      - name: Install Dist::Zilla
        env:
          PERL_CPANM_OPT: --mirror http://cpan.metacpan.org --mirror-only
        run: cpanm -nq Dist::Zilla Dist::Zilla::PluginBundle::Author::GETTY && dzil install
      - name: Install dependencies
        env:
          PERL_CPANM_OPT: --mirror http://cpan.metacpan.org --mirror-only
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --missing | cpanm -nq
      - name: Force share build
        env:
          ALIEN_INSTALL_TYPE: share
        run: dzil test
